[versions]
maven-group = "band.kessokuteatime"
archives-name = "poemofstarwars"
mod = "1.0.1"
loader = "fabric"

minecraft = "1.20.2"
yarn = "1.20.2+build.4"
fabric-loader = "0.16.0"
fabric-api = "0.91.6+1.20.2"
fabric-loom = "1.6-SNAPSHOT"
modpublisher = "2.1.0"

# id
id-modrinth = "fPybV5rf"
id-curseforge = "1006177"

# display
display-name = "Poem o' Star Wars"
display-loader = "Fabric"
display-version = "1.20.2~1.20.6"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
yarn = { group = "net.fabricmc", name = "yarn", version.ref = "yarn" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
modpublisher = { id = "com.hypherionmc.modutils.modpublisher", version.ref = "modpublisher" }

[bundles]
fabric = ["fabric-loader", "fabric-api"]
